### ISSUE TITLE
I got error Please help

### ISSUE THREAD

**Issue by PrashantKT** [dreadkopp/8470p_10.13.x#1]
While Installing before using your files I was not able to move my mouse. when I use your files i can able to move mouse and keyboard is also working fine. But after that I got 

macos could not be installed on your computer high sierra. 

Could you please help me to fix this ?

**Comment by dreadkopp** [comment]
would need more info. make sure you create your installer with fresh image form appstore, use createinstallmedia for createion with downloadassets flag (for mojave) wipe drive before installing ... Just successfully updated to mojave on my machine without (bigger ) problems
