### ISSUE TITLE
Fail to boot after installed Xcode 10

### ISSUE THREAD

**Issue by dangquoctuan** [dreadkopp/8470p_10.13.x#2]
Hello, I'm using your EFI folder to boot my hackcintosh with HP 8470p model i5 3320M, no VGA. After I installed Xcode 10, I can't boot into macOS Mojave 10.14.3. The screen appears with 4 colors. I downloaded EFI folder from branch 10.14. This's my video error https://drive.google.com/file/d/1DoainpwUcn9gv4sduFEM7WQ9BAGZZooG/view?usp=sharing  Please help!! Thank you..

**Comment by dreadkopp** [comment]
Hey. Xcode is running fine for me. Looks like a problem with the
framebuffer. Never saw that behavior though. Tried booting in safe Mode and
/ or tried an external Monitor?

Am Mi., 6. Feb. 2019, 09:57 hat dangquoctuan <notifications@github.com>
geschrieben:
